services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
    volumes:
      - 'ollama_data:/root/.ollama'
    # networks:
    #   - Lab_network

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=tinkerersLab'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    expose:
      - '5432'
  #   networks:
  #     - Lab_network

  # networks:
  #   Lab_network:
  #     driver: bridge
  volumes:
    ollama_data:
