services:
  # uncomment this in case you want to run ollama inside a docker container
  # ollama:
  #   image: 'ollama/ollama:latest'
  #   ports:
  #     - '11434:11434'
  #   expose:
  #     - '11434'
  #   volumes:
  #     - 'ollama_data:/root/.ollama'

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=tinkerersLab'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    expose:
      - '5432'
